/* =========================================================
   v2.4 后台「进化设计与校验」：NameAnchorValidator / EvolutionDesignEditor / PartBasisViewer / CommonElementRuleChecker / SilhouetteDiffChecker /
   StageMutationChecker / CategoryDiffChecker / CrossCategoryDiffChecker / GroundAuraChecker / SkinAppearanceChecker / EvolutionValidationPanel / PublishGate
========================================================= */
SP_ART_TABS.evo = ['进化设计与校验','Evolution design & checks','Thiết kế tiến hóa & kiểm tra'];
function spArtEvoHtml(){
  const S = spS(), d = spArtSample(), F = spEvoFlags(), AL = spEvoAllow(d), D = spEvoDesign(d), V = spEvoValidate(d), doc = spEvoDoc(d.id), g = spGene(d);
  const yes = b=>b ? `✅ ${escapeHtml(tx('通过','Pass','Đạt'))}` : `⛔ ${escapeHtml(tx('未通过','Fail','Chưa đạt'))}`;
  const flags = SP_EVO_FLAGS.map(([k, key, n])=>`<label class="chipcheck"><input type="checkbox" name="ef_${k}" ${F[k]?'checked':''}> ${spArtE(n)} <code class="mono" data-i18n-ignore="1">${key}</code></label>`).join('') + `<label class="chipcheck"><input type="checkbox" checked disabled> ${escapeHtml(tx('禁止脚下光圈 / 地圈 / 法阵 / 地面辉光','No ground aura / ring / circle / floor glow','Cấm vòng / trận / ánh sáng dưới chân'))} <code class="mono" data-i18n-ignore="1">evolution_ground_aura_forbidden</code> 🔒</label>`;
  const wl = spArtT([tx('通用元素','Common element','Yếu tố chung'), tx('白名单','Whitelist','Danh sách trắng'), tx('本精灵','This spirit','Tinh linh này'), tx('依据','Basis','Căn cứ')], [['wings',['翅膀','Wings','Cánh']],['halo',['光环（非脚下）','Aura (never at the feet)','Vầng (không dưới chân)']],['crown',['皇冠','Crown','Vương miện']],['tail',['尾巴','Tail','Đuôi']],['ext',['能量形态延伸','Energy-form extension','Phần kéo dài năng lượng']]].map(([k,n])=>[`<b>${spArtE(n)}</b>`, `<small data-i18n-ignore="1">${escapeHtml(SP_EVO_WL[k].join(' · '))}</small>`, AL[k] ? `✅ ${escapeHtml(tx('允许','Allowed','Cho phép'))}` : `🚫 ${escapeHtml(tx('禁止','Not allowed','Cấm'))}`, AL.why[k] ? spArtE(AL.why[k]) : '—']));
  const basis = spArtT([tx('阶段','Stage','Giai đoạn'), tx('进化方向','Direction','Hướng'), tx('依据','Basis','Căn cứ')], [...g.d4.map(k=>['LV4', spArtE(SP_D4[k].n), spDirBasis(d,k) ? spArtE(spDirBasis(d,k)) : '⛔']), ...g.d5.map(k=>['LV5', spArtE(SP_D5[k].n), spDirBasis(d,k) ? spArtE(spDirBasis(d,k)) : '⛔'])]);
  const stages = spArtT([tx('阶段','Stage','Giai đoạn'), tx('名称','Name','Tên'), tx('形态','Form','Hình'), tx('剪影','Silhouette','Bóng'), tx('名称推导','From the name','Từ tên'), tx('部件','Parts','Bộ phận'), tx('材质','Materials','Chất liệu')], D.stages.map(s=>[`LV${s.st}`, `<b data-i18n-ignore="1">${escapeHtml(s.name)}</b>`, spiritView(d, 64, s.st, {nofx:true}), spiritView(d, 52, s.st, {silhouette:true, nofx:true}), s.mods.map(m=>spArtE(SP_NAME_KW.find(r=>r[0]===m)[2])).join('<br>') || escapeHtml(s.st<=2 ? tx('主体词本形','The subject itself','Bản thể chủ đề') : '—'), `<small>${s.parts.map(escapeHtml).join(' · ')}</small>`, `<small>${s.mats.map(m=>escapeHtml(trT(SP_ART_MAT[m]?.[1] || SP_MNODE_TX_N[m] || [m,m,m]))).join(' · ') || '—'}</small>`]), 'sp-art-stage');
  const checks = `<ul class="sp-evo-checks">${V.list.map(c=>`<li class="${c.ok?'ok':'bad'}"><b>${c.ok?'✅':'⛔'} ${spArtE(SP_EVO_CHECKS.find(x=>x[0]===c.k)[1])}</b> <span>${spArtE(c.msg)}</span></li>`).join('')}</ul><p class="sp-evo-gate ${V.ok?'ok':'bad'}">${V.ok ? `🟢 ${escapeHtml(tx('发布门禁：可以发布','Publish gate: OK to publish','Cổng phát hành: được phát hành'))}` : `🔴 ${escapeHtml(tx('发布门禁：未通过校验，禁止发布','Publish gate: checks failed — publishing blocked','Cổng phát hành: chưa đạt — chặn phát hành'))}`}</p>`;
  const ed = `<form id="spEvoDocForm" class="sp-form" onsubmit="return false" data-id="${escapeAttr(d.id)}"><div class="sp-form-row"><label>${escapeHtml(tx('主体词','Subject word','Từ chủ đề'))}<input name="subject" value="${escapeAttr(doc.subject||'')}" placeholder="${escapeAttr(D.subject)}" data-i18n-ignore="1"></label></div>
    <div class="sp-form-row">${[1,2,3,4,5].map(n=>`<label>LV${n} ${escapeHtml(tx('形态','form','hình'))}<input name="form${n}" value="${escapeAttr(doc['form'+n]||'')}" placeholder="${escapeAttr(D.stages[n-1].name)}" data-i18n-ignore="1"></label>`).join('')}</div>
    <div class="sp-form-row">${['wings','halo','crown','tail'].map(k=>`<label>${spArtE({wings:['翅膀','Wings','Cánh'], halo:['光环','Aura','Vầng'], crown:['皇冠','Crown','Vương miện'], tail:['尾巴','Tail','Đuôi']}[k])}${spSel('w_'+k, [['', tx('按白名单','Per whitelist','Theo danh sách')], ['allow', tx('允许（需写依据）','Allow (basis needed)','Cho phép (cần căn cứ)')], ['deny', tx('禁止','Deny','Cấm')]], doc[k]||'')}<input name="why_${k}" value="${escapeAttr(doc[k+'Why']||'')}" placeholder="${escapeAttr(tx('依据，如：设定为焰凤','Basis, e.g. "designed as a flame phoenix"','Căn cứ'))}" data-i18n-ignore="1"></label>`).join('')}</div>
    <label>${escapeHtml(tx('质变说明','Transformation notes','Ghi chú biến đổi'))}<textarea name="mut" rows="2" data-i18n-ignore="1" placeholder="${escapeAttr(D.mut)}">${escapeHtml(doc.mut||'')}</textarea></label>
    <div class="sp-form-act"><button type="button" class="btn btn-primary btn-sm" data-act="spEvoDocSave">${escapeHtml(tx('保存进化设计文档','Save the evolution design','Lưu thiết kế tiến hóa'))}</button></div></form>`;
  /* 全库校验（EvolutionValidationPanel） */
  const L = spLib().filter(x=>x.enabled!==false), only = S.evoBad, rows = []; let pass = 0;
  L.forEach(x=>{ const r = spEvoValidate(x); if(r.ok) pass++; if(only && r.ok) return; if(rows.length<80) rows.push([`<button type="button" class="linklike" data-act="spArtSampleId" data-v="${escapeAttr(x.id)}">${escapeHtml(trT(x.name))}</button>`, escapeHtml(spArtCatName(spArtCatKey(x))), escapeHtml(trT(SP_PUB_ST?.[x.pub?.status] || [x.pub?.status||'',x.pub?.status||'',x.pub?.status||''])), ...r.list.map(c=>c.ok?'✅':'⛔')]); });
  const panel = `<p>${escapeHtml(tx(`共 ${L.length} 只，通过 ${pass} 只，未通过 ${L.length-pass} 只`, `${L.length} spirits: ${pass} pass, ${L.length-pass} fail`, `${L.length} tinh linh: ${pass} đạt, ${L.length-pass} chưa đạt`))} <button type="button" class="btn btn-ghost btn-sm" data-act="spEvoBad" aria-pressed="${!!only}">${escapeHtml(only?tx('显示全部','Show all','Hiện tất cả'):tx('只看未通过','Failures only','Chỉ xem chưa đạt'))}</button></p>` + spArtT([tx('精灵','Spirit','Tinh linh'), tx('类别','Category','Hệ'), tx('状态','Status','Trạng thái'), ...SP_EVO_CHECKS.map(c=>trT(c[1]))], rows, 'sp-evo-tbl');
  return spArtCard(`🧭 ${escapeHtml(tx('名称即设定 · 全局配置','Name is the setting · global configuration','Tên là thiết lập · cấu hình'))}`, `<form id="spEvoForm" class="sp-form" onsubmit="return false"><div class="sp-chipchecks">${flags}</div><div class="sp-form-act"><button type="button" class="btn btn-primary btn-sm" data-act="spEvoSave">${escapeHtml(tx('保存','Save','Lưu'))}</button></div></form>`)
    + spArtCard(`📜 ${escapeHtml(tx('进化设计文档（EvolutionDesignEditor）','Evolution design document (EvolutionDesignEditor)','Tài liệu thiết kế tiến hóa'))}`, spArtSampleSel() + `<p><b>${escapeHtml(tx('主体词','Subject','Chủ đề'))}</b> <span data-i18n-ignore="1">${escapeHtml(D.subject)}</span> · <b>${escapeHtml(tx('进化方向','Direction','Hướng'))}</b> <span data-i18n-ignore="1">${escapeHtml(D.dir)}</span></p>` + stages + `<p class="hint">${escapeHtml(tx('质变说明','Transformation','Biến đổi'))}：${escapeHtml(D.mut)}</p>` + ed)
    + spArtCard(`✅ ${escapeHtml(tx('十二项校验 + 发布门禁（PublishGate）','Twelve checks + publish gate (PublishGate)','Mười hai kiểm tra + cổng phát hành'))}`, checks)
    + spArtCard(`🪽 ${escapeHtml(tx('通用元素规则（CommonElementRuleChecker）','Common-element rules (CommonElementRuleChecker)','Quy tắc yếu tố chung'))}`, wl)
    + spArtCard(`🧩 ${escapeHtml(tx('部件依据（PartBasisViewer）','Part basis (PartBasisViewer)','Căn cứ bộ phận'))}`, basis)
    + spArtCard(`📋 ${escapeHtml(tx('全库进化校验（EvolutionValidationPanel）','Library-wide checks (EvolutionValidationPanel)','Kiểm tra toàn kho'))}`, panel);
}
/* 操作员：图鉴详情里的进化设计摘要（名称 → 形态） */
function spCxDetailExtra(def, on, me){
  let h = spCxDetailExtraArtCore(def, on, me); if(!on || !def || !def.forms) return h;
  try{ const D = spEvoDesign(def); h += `<dt>${escapeHtml(tx('进化设计','Evolution design','Thiết kế tiến hóa'))}</dt><dd><small>${escapeHtml(tx('主体词','Subject','Chủ đề'))}「<span data-i18n-ignore="1">${escapeHtml(D.subject)}</span>」 · ${D.stages.filter(s=>s.mods.length).map(s=>`LV${s.st} ${s.mods.map(m=>escapeHtml(trT(SP_NAME_KW.find(r=>r[0]===m)[2]).split(/[：:]/)[0])).join(' / ')}`).join(' · ')}</small></dd>`; }catch(_e){}
  try{ if(typeof spCxPathRows==='function') h += spCxPathRows(def, on, me); }catch(_e){}
  return h;
}
function spAction16(act, el, id){
  const S = spS();
  switch(act){
    case 'spArtSampleId': S.artSample = el?.dataset?.v; return true;
    case 'spEvoBad': S.evoBad = !S.evoBad; return true;
    case 'spEvoSave': { if(!spIsAdmin()) return false; const fd = new FormData(document.getElementById('spEvoForm')), flags = {}; SP_EVO_FLAGS.forEach(([k])=>flags[k] = fd.get('ef_'+k)==='on');
      G().config = {...gCfg(), evoCfg:{...(gCfg().evoCfg||{}), flags}, updatedAt:gNowIso(), updatedBy:spMe()}; spAuditCore('evo-config', '', flags); spCacheVer++; spGeneCache?.clear?.(); saveGrowth(true); toast(tx('已保存','Saved','Đã lưu'), 'ok'); return true; }
    case 'spEvoDocSave': { if(!spIsAdmin()) return false; const f = document.getElementById('spEvoDocForm'), fd = new FormData(f), did = f.dataset.id, o = {};
      ['subject','mut','form1','form2','form3','form4','form5'].forEach(k=>{ const v = String(fd.get(k)||'').trim(); if(v) o[k] = v; });
      for(const k of ['wings','halo','crown','tail']){ const m = String(fd.get('w_'+k)||''), why = String(fd.get('why_'+k)||'').trim(); if(m==='allow' && !why){ toast(tx('允许通用元素必须写依据','Allowing a common element needs a basis','Cho phép yếu tố chung cần căn cứ'), 'warn'); return false; } if(m){ o[k] = m; if(why) o[k+'Why'] = why; } }
      const E = gCfg().evoCfg || {}; G().config = {...gCfg(), evoCfg:{...E, docs:{...(E.docs||{}), [did]:o}}, updatedAt:gNowIso(), updatedBy:spMe()}; spAuditCore('evo-doc', did, {}); spCacheVer++; spGeneCache?.clear?.(); saveGrowth(true); toast(tx('已保存','Saved','Đã lưu'), 'ok'); return true; }
  }
  return spAction16Core(act, el, id);
}
Object.assign(SP_AUDIT_LABEL, {'evo-config':['进化校验配置','Evolution check settings','Cấu hình kiểm tra tiến hóa'], 'evo-doc':['进化设计文档','Evolution design document','Tài liệu thiết kế tiến hóa']});
